<?php

/**
 * @file
 * A module exemplifying Drupal's coding standards.
 *
 * This module provides a block that lists all of the installed modules.
 */

/**
 * Implements hook_help().
 */
function first_help($path, $arg) {
  if ($path == 'admin/help#first') {
    return t('A demo module.');
  }
}

/**
 * Implements hook_block_info().
 */
function first_block_info() {
  $blocks = array();
  $blocks['list_modules'] = array(
    'info' => t('A listing of all enabled modules'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function first_block_view($block_name) {
  if ($block_name == 'list_modules') {
    $list = module_list();
    foreach ($list as $key) {
      $list[$key] = strrev($key);
    }
    asort($list);
    $theme_args = array(
      'items' => $list,
      'type' => 'ol',
    );
    $content = theme('item_list', $theme_args);
    $block = array(
      'subject' => t('Enabled modules'),
      'content' => $content,
    );

    return $block;
  }
}
